package noorg.kloud.vthelper.data.dbentities.mano

import androidx.room.ColumnInfo
import androidx.room.Embedded
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey
import androidx.room.Relation

@Entity(
    tableName = "mano_settlement_grades",
    foreignKeys = [
        ForeignKey(
            entity = DBManoSettlementGroup::class,
            parentColumns = arrayOf("composite_pk_id"),
            childColumns = arrayOf("composite_settlement_pk_id"),
            onUpdate = ForeignKey.CASCADE,
            onDelete = ForeignKey.CASCADE
        ),
        ForeignKey(
            entity = DBManoEmployeeEntity::class,
            parentColumns = arrayOf("mano_id"),
            childColumns = arrayOf("grader_id"),
            onUpdate = ForeignKey.CASCADE,
            onDelete = ForeignKey.CASCADE
        )
    ]
)
data class DbManoSettlementGrade(

    // To be generated by combining group composite id and name
    @PrimaryKey(autoGenerate = false)
    @ColumnInfo(name = "composite_pk_id")
    val compositePrimaryId: String,

    //  subjectModId + semesterAbsoluteSequenceNum + settlementType
    @ColumnInfo(name = "composite_settlement_pk_id")
    val compositeSettlementId: String,

    @ColumnInfo(name = "name")
    val name: String,
    @ColumnInfo(name = "value")
    val value: Int?,
    @ColumnInfo(name = "date")
    val date: String?,

    @ColumnInfo(name = "grader_id")
    val graderId: Long
)

data class DbManoSettlementGradeWithEmployee(
    @Embedded
    val grade: DbManoSettlementGrade,
    @Relation(
        parentColumn = "grader_id",
        entityColumn = "mano_id"
    )
    val employee: DBManoEmployeeEntity
)

fun getSettlementGradeCompositeKey(semesterAbsoluteSequenceNum: Int, subjectModId: Int, settlementType: String, name: String): String {
    return "${getSettlementGroupCompositeKey(semesterAbsoluteSequenceNum, subjectModId, settlementType)}-name_$name"
}

