package noorg.kloud.vthelper.data.dbentities.mano

import androidx.room.ColumnInfo
import androidx.room.Embedded
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import androidx.room.Relation

@Entity(
    tableName = "mano_settlement_groups",
    foreignKeys = [
        ForeignKey(
            entity = DBManoSubjectEntity::class,
            parentColumns = arrayOf("composite_pk_id"),
            childColumns = arrayOf("composite_subject_pk_id"),
            onUpdate = ForeignKey.CASCADE,
            onDelete = ForeignKey.CASCADE
        ),
        ForeignKey(
            entity = DBManoSemesterEntity::class,
            parentColumns = arrayOf("absolute_seq"),
            childColumns = arrayOf("sem_absolute_seq"),
            onUpdate = ForeignKey.CASCADE,
            onDelete = ForeignKey.CASCADE
        ),
    ],
    indices = [
        Index("sem_absolute_seq"),
        Index("composite_subject_pk_id"),
    ]
)
class DBManoSettlementGroup (
    // To be generated by combining subjectModId, semesterAbsoluteSequenceNum and settlementType
    @PrimaryKey(autoGenerate = false)
    @ColumnInfo(name = "composite_pk_id")
    val compositePrimaryId: String,

    // subjectModId + semesterAbsoluteSequenceNum
    // FK to mano_subjects
    @ColumnInfo(name = "composite_subject_pk_id")
    val compositeSubjectId: String,

    @ColumnInfo(name = "settlement_type")
    val settlementType: String,
    @ColumnInfo(name = "subject_mod_id")
    val subjectModId: Int,
    // FK to mano_semesters
    @ColumnInfo(name = "sem_absolute_seq")
    val semesterAbsoluteSequenceNum: Int,

    @ColumnInfo(name = "completed_ratio")
    val completedRatio: String,

    @ColumnInfo(name = "final_assessment_percentage")
    val percentageOfFinalAssessment: Int,
    @ColumnInfo(name = "final_grade")
    val finalGrade: Float?,
    @ColumnInfo(name = "final_cumulative_score")
    val finalCumulativeScore: Float?,

    @ColumnInfo(name = "last_updated")
    val lastUpdatedDate: String?
)

data class DBManoSettlementGroupWithGrades(
    @Embedded
    val group: DBManoSettlementGroup,
    @Relation(
        // https://developer.android.com/training/data-storage/room/relationships/nested
        // Important. Used by room to determine the underlying entity for DbManoSettlementGradeWithEmployee
        entity = DbManoSettlementGrade::class,
        parentColumn = "composite_pk_id",
        entityColumn = "composite_settlement_pk_id"
    )
    val grades: List<DbManoSettlementGradeWithEmployee>
)

fun getSettlementGroupCompositeKey(semesterAbsoluteSequenceNum: Int, subjectModId: Int, settlementType: String): String {
    return "${getSubjectCompositeKey(semesterAbsoluteSequenceNum, subjectModId)}-type_$settlementType"
}