package noorg.kloud.vthelper.data.dbentities.mano

import androidx.compose.ui.graphics.Color
import androidx.room.ColumnInfo
import androidx.room.Embedded
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey
import androidx.room.Relation

enum class DBManoSubjectEvaluationVerdict(v: String) {
    PASS("T"),
    FAIL("R"),
    FAILED_TO_APPEAR("P"), // P - failed to disappear
    FAILED_DISHONESTY("N"), // N - not certified due to dishonesty
    FAILED_UNMETHODICAL("G"), // G - not certified due to unmethodical work
}

@Entity(
    tableName = "mano_subjects",
    foreignKeys = [
        ForeignKey(
            entity = DBManoSemesterEntity::class,
            parentColumns = arrayOf("absolute_seq"),
            childColumns = arrayOf("semester_absolute_seq"),
            onUpdate = ForeignKey.CASCADE,
            onDelete = ForeignKey.CASCADE
        ),
        ForeignKey(
            entity = DBManoEmployeeEntity::class,
            parentColumns = arrayOf("mano_id"),
            childColumns = arrayOf("lecturer_id"),
            onUpdate = ForeignKey.CASCADE,
            onDelete = ForeignKey.CASCADE
        )
    ]
)
data class DBManoSubjectEntity(
    // To be generated by combining modId and semesterAbsoluteSeq
    @PrimaryKey(autoGenerate = false)
    @ColumnInfo(name = "composite_pk_id")
    val compositePrimaryId: String,

    @ColumnInfo(name = "mod_id")
    val modId: Int,
    @ColumnInfo(name = "mod_code")
    val modCode: String,
    @ColumnInfo(name = "link")
    val link: String,

    // TODO: extract custom colors into preferences and base them on the modCode
    @ColumnInfo(name = "custom_color")
    val customColor: Long? = null,

    // FK to mano_semesters
    @ColumnInfo(name = "semester_absolute_seq")
    val semesterAbsoluteSeq: Int,

    // FK to mano_employees
    @ColumnInfo(name = "lecturer_id")
    val lecturerId: Long,

    @ColumnInfo(name = "name")
    val name: String,

    // Available only after fetching mediate results
    @Embedded
    val mediateData: DBManoSubjectMediateData,

    // After completing this subject
    @ColumnInfo(name = "tries")
    val tries: Int? = null,
    @ColumnInfo(name = "hours")
    val hours: Int? = null,
    // Fetchable from https://mano.vilniustech.lt/program/site, but right now only after completing the subject
    // TODO: Fetch this and make not null
    @ColumnInfo(name = "credits")
    val credits: Int? = null,

    @ColumnInfo(name = "final_completion_date")
    val finalCompletionDate: String? = null,
    @ColumnInfo(name = "final_completion_grade")
    val finalCompletionGrade: Int? = null,
    @ColumnInfo(name = "final_evaluation_verdict")
    val finalEvaluationVerdict: DBManoSubjectEvaluationVerdict? = null,
)

data class DBManoSubjectMediateData(
    @ColumnInfo(name = "ta_ga_split_percentage")
    val taGaSplitPercentage: String? = null,
    @ColumnInfo(name = "mediate_results_available")
    val mediateResultsAvailable: Boolean = false,

    @ColumnInfo(name = "final_completion_cumulative_score")
    val finalCompletionCumulativeScore: String? = null,
    @ColumnInfo(name = "final_completion_credit_score")
    val finalCompletionCreditScore: String? = null,
)

// https://developer.android.com/training/data-storage/room/relationships/one-to-one
// https://medium.com/androiddevelopers/7-pro-tips-for-room-fbadea4bfbd1
// https://proandroiddev.com/room-database-lessons-learnt-from-working-with-multiple-tables-d499c9be94ce

data class DBManoSubjectEntityWithEmployee(
    @Embedded
    val subject: DBManoSubjectEntity,
    @Relation(
        parentColumn = "lecturer_id",
        entityColumn = "mano_id"
    )
    val employee: DBManoEmployeeEntity
)

fun getSubjectCompositeKey(semesterAbsoluteSequenceNum: Int, subjectModId: Int): String {
    return "sem_$semesterAbsoluteSequenceNum-sub_$subjectModId"
}